version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - "backend/.env"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
